### ISSUE TITLE
[Feature] Possible option to change clock position

### ISSUE THREAD

**Issue by szczepix** [thibmo/GUI-Clock-Fabric#1]
As a player who using this mod, I want to change clock position like:

- top-left
- top-center
- top-right
- center-left
- center-center
- center-right
- bottom-left -> set as default for backward compatibility settings
- bottom-center
- bottom-right

so I can choose where I want to see the clock.

**Comment by LauraRozier** [comment]
Working on this now.
Trying with enums first, if that works nicely I'll have an update today.

**Comment by LauraRozier** [comment]
Implemented in 2.5, curseforge is processing it now.
